# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SanihubRamales
                                 A QGIS plugin
 sanihub.org
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-02-24
        copyright            : (C) 2021 by BID - SaniHUB
        email                : info@sanihub.org
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SanihubRamales class from file SanihubRamales.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .sanihub_ramales import SanihubRamales
    return SanihubRamales(iface)
